apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "chouette.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
spec:
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas}}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas}}
  metrics:
    - external:
        metric:
          name: pubsub.googleapis.com|subscription|num_undelivered_messages
          selector:
            matchLabels:
              resource.labels.subscription_id: chouette_poll_status_queue
              resource.labels.project_id: entur-ror-dev
        target:
          type: AverageValue
          averageValue: 1
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "chouette.name" . }}