replicas: 3
image:
  identifier: <+artifacts.primary.image>

service:
  http:
    externalPort: 80
    internalPort: 8080

resources:
  cpuLimit: "3"
  memLimit: 22000Mi
  cpuRequest: "2"
  memRequest: 22000Mi
  xmx: 18g

secrets:
  chouette-psql-credentials:
    - CHOUETTE_DATABASE_USERNAME
    - CHOUETTE_DATABASE_PASSWORD
    - CHOUETTE_IEV_DATABASE_USERNAME
    - CHOUETTE_IEV_DATABASE_PASSWORD
  chouette-iev-credentials:
    - IEV_REFERENTIAL_ADMIN_INITIAL_ENCRYPTED_PASSWORD
    - IEV_REFERENTIAL_USER_INITIAL_ENCRYPTED_PASSWORD
