replicas: 3
image:
  identifier: ${artifact.metadata.image}

service:
  http:
    externalPort: 80
    internalPort: 8080

resources:
  cpuLimit: "5"
  memLimit: 15000Mi
  cpuRequest: "4"
  memRequest: 14500Mi
  xmx: 13g
