replicas: 3
image:
  identifier: ${artifact.metadata.image}

service:
  http:
    externalPort: 80
    internalPort: 8080

resources:
  cpuLimit: "3"
  memLimit: 22000Mi
  cpuRequest: "2"
  memRequest: 22000Mi
  xmx: 18g
