name: Build, push and deploy
on:
  push:
    branches:
      - rutebanken_develop
  pull_request:
    branches:
      - rutebanken_develop
env:
  PG_HOST: postgres
  PG_PORT: 5432
jobs:
  maven-verify:
    runs-on: ubuntu-24.04
    container: cimg/openjdk:17.0.17
    services:
        postgres:
            image: postgis/postgis:13-3.5
            env:
             TZ: Europe/Oslo
             POSTGRES_DB: chouette_test
             POSTGRES_USER: chouette
             POSTGRES_PASSWORD: chouette
            options: >-
              --health-cmd pg_isready 
              --health-interval 10s 
              --health-timeout 5s 
              --health-retries 5
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Cache Maven dependencies
          uses: actions/cache@v4
          with:
            # Run mvn help:evaluate -Dexpression=settings.localRepository -s .github/workflows/settings.xml
            # to find the location of the Maven cache in the container
            path: /home/circleci/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              ${{ runner.os }}-maven-
              ${{ runner.os }}-
        - name: Run maven build
          run: mvn -DskipWildfly -DskipDelombok -Ddb.host=postgres -B clean install
        - name: Sonar Scan
          env:
              SONAR_TOKEN: ${{ secrets.ENTUR_SONAR_PASSWORD }}
              SONAR_PROJECT_NAME: ${{ github.event.repository.name }}
              SONAR_PROJECT_KEY: entur_${{ github.event.repository.name }}
          run: |
            mvn -Psonar \
                    org.jacoco:jacoco-maven-plugin:prepare-agent verify \
                    org.jacoco:jacoco-maven-plugin:report sonar:sonar \
                    -Ddb.host=postgres \
                    -Dmaven.main.skip \
                    -DskipTests \
                    -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                    -Dsonar.organization=enturas-github \
                    -Dsonar.projectName=${SONAR_PROJECT_NAME} \
                    -Dsonar.host.url=https://sonarcloud.io \
                    -Dsonar.token=${SONAR_TOKEN}
        - name: Upload artifact
          uses: actions/upload-artifact@v7.0.1
          with:
            path: |
              target/docker/wildfly/
              chouette_iev/target/chouette.ear
            if-no-files-found: error

  docker-build:
          if: github.repository_owner == 'entur' && github.event_name == 'push' && github.ref == 'refs/heads/rutebanken_develop'
          needs: [ maven-verify ]
          uses: entur/gha-docker/.github/workflows/build.yml@v1
          with:
            build_artifact_name: artifact
            build_artifact_path: ~
  docker-push:
          needs: [ docker-build ]
          uses: entur/gha-docker/.github/workflows/push.yml@v1


  helm-lint:
    uses: entur/gha-helm/.github/workflows/lint.yml@v1
    with:
      environment: dev


  deploy-dev:
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && github.ref == 'refs/heads/rutebanken_develop' }}
    needs: [ helm-lint, docker-push ]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
      chart: helm/chouette
      image_set_path: "image.identifier"
      namespace: chouette
      release_name: chouette
    secrets: inherit

  approval-tst:
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && github.ref == 'refs/heads/rutebanken_develop' }}
    needs: [ deploy-dev, helm-lint, docker-push ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: Approve
    steps:
      - name: Manual approval
        shell: bash
        run: echo "Approve TST deployment"

  deploy-tst:
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && github.ref == 'refs/heads/rutebanken_develop' }}
    needs: [ approval-tst, docker-push ]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: tst
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
      chart: helm/chouette
      image_set_path: "image.identifier"
      namespace: chouette
      release_name: chouette
    secrets: inherit

  approval-prd:
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && github.ref == 'refs/heads/rutebanken_develop' }}
    needs: [ deploy-tst, approval-tst, docker-push ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: Approve
    steps:
      - name: Manual approval
        shell: bash
        run: echo "Approve PRD deployment"

  deploy-prd:
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && github.ref == 'refs/heads/rutebanken_develop' }}
    needs: [ approval-prd, docker-push ]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: prd
      image: ${{ needs.docker-push.outputs.image_name }}:${{ needs.docker-push.outputs.image_tag}}
      chart: helm/chouette
      image_set_path: "image.identifier"
      namespace: chouette
      release_name: chouette
    secrets: inherit